// Generated by tools/assets/cuisine.py; edit catalog definitions there.
package darkspawn.black.cooking;

import darkspawn.black.Darkspawn;
import darkspawn.black.boss.BossKind;
import java.util.*;
import java.util.function.Function;
import net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents;
import net.minecraft.core.*;
import net.minecraft.core.registries.*;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;

public final class Cuisine {
 public record Dish(Item item, String category, String discovery) {}
 public static final Map<String, Dish> DISHES = new LinkedHashMap<>();
 public static final Map<String, Item> SCROLLS = new LinkedHashMap<>();
 public static final Map<BossKind, Item> INGREDIENTS = new EnumMap<>(BossKind.class);
 public static final Map<BossKind, Item> TROPHIES = new EnumMap<>(BossKind.class);
 public static final Item COOKBOOK = register("cookbook", p -> new CookbookItem(p.stacksTo(1)));
 private Cuisine() {}
 public static <T extends Item> T register(String name, Function<Item.Properties,T> factory) {
  var key = ResourceKey.create(Registries.ITEM, Darkspawn.id(name));
  return Registry.register(BuiltInRegistries.ITEM, key, factory.apply(new Item.Properties().setId(key)));
 }
 private static BlockBehaviour.Properties blockProperties(String name) {
  return BlockBehaviour.Properties.of().setId(ResourceKey.create(Registries.BLOCK, Darkspawn.id(name))).strength(1).noOcclusion().sound(SoundType.WOOD);
 }
 private static Item blockItem(String name, Block block) {
  Registry.register(BuiltInRegistries.BLOCK, Darkspawn.id(name), block);
  BlockItem item = register(name, p -> new BlockItem(block, p.useBlockDescriptionPrefix()));
  item.registerBlocks(Item.BY_BLOCK, item);
  return item;
 }
 private static void addMeal(String name, Holder<MobEffect> effect, int hunger, int seconds, String category, String discovery, boolean bowl) {
  MealItem item = register(name, p -> {
   p.stacksTo(16).food(new FoodProperties.Builder().nutrition(hunger).saturationModifier(0.8F).alwaysEdible().build());
   if (bowl) p.usingConvertsTo(Items.BOWL);
   return new MealItem(p, effect, seconds * 20);
  });
  DISHES.put(name, new Dish(item, category, discovery));
  if (!discovery.isEmpty()) SCROLLS.put(name, register(name + "_scroll", p -> new RecipeScrollItem(p, name)));
 }
 private static void addFeast(String name, Holder<MobEffect> effect, String discovery) {
  DISHES.put(name, new Dish(blockItem(name, new FeastBlock(blockProperties(name), effect)), "Feasts", discovery));
  if (!discovery.isEmpty()) SCROLLS.put(name, register(name + "_scroll", p -> new RecipeScrollItem(p, name)));
 }
 public static boolean canCook(net.minecraft.world.entity.player.Player player, String name) {
  Dish dish = DISHES.get(name);
  return dish == null || dish.discovery().isEmpty() || Culinary.progress(player).knows(name);
 }
 public static void initialize() {
  INGREDIENTS.put(BossKind.ANCIENT_TREE_SPIRIT, register("ancient_sap", Item::new));
  INGREDIENTS.put(BossKind.MUTANT_WOLF, register("prime_beast_meat", Item::new));
  INGREDIENTS.put(BossKind.MUTANT_ZOMBIE, register("restored_marrow", Item::new));
  INGREDIENTS.put(BossKind.FOSSIL_TYRANT, register("marrow_extract", Item::new));
  INGREDIENTS.put(BossKind.THUNDER_BIRD, register("charged_yolk", Item::new));
  INGREDIENTS.put(BossKind.TITAN_BOA, register("titan_meat", Item::new));
  INGREDIENTS.put(BossKind.BABA_YAGA, register("witch_spice", Item::new));
  INGREDIENTS.put(BossKind.MOUNTAIN_TITAN, register("mineral_salt", Item::new));
  INGREDIENTS.put(BossKind.ICE_WYRM, register("wyrm_fat", Item::new));
  INGREDIENTS.put(BossKind.KRAKEN, register("kraken_meat", Item::new));
  INGREDIENTS.put(BossKind.CAVE_CRAWLER, register("cave_truffle", Item::new));
  INGREDIENTS.put(BossKind.SHADOW_CREEPER_QUEEN, register("royal_jelly", Item::new));
  INGREDIENTS.put(BossKind.MYCELIAL_SOVEREIGN, register("sovereign_cap", Item::new));
  INGREDIENTS.put(BossKind.NETHERBORN, register("infernal_marrow", Item::new));
  INGREDIENTS.put(BossKind.SOULBOUND_COLOSSUS, register("soul_salt", Item::new));
  INGREDIENTS.put(BossKind.VOID_EYE, register("void_essence", Item::new));
  addMeal("hunters_stew", MealEffects.HUNTER, 8, 180, "Taiga", "", false);
  addMeal("farmhouse_roast", MealEffects.HEARTY, 8, 180, "Plains", "", false);
  addMeal("spiced_steak", MealEffects.FIREPROOF, 8, 180, "Desert", "", false);
  addMeal("tropical_skewer", MealEffects.IRON_STOMACH, 8, 180, "Jungle", "", false);
  addMeal("bog_gumbo", MealEffects.IRON_STOMACH, 8, 180, "Swamp", "Journeyman Chef", false);
  addMeal("miners_meal", MealEffects.MINER, 8, 180, "Mountains", "", false);
  addMeal("winter_hotpot", MealEffects.WARMING, 8, 180, "Frozen", "", false);
  addMeal("seafood_rice", MealEffects.DEEP_BREATH, 8, 180, "Ocean", "", false);
  addMeal("mushroom_risotto", MealEffects.SUSTAINED, 8, 180, "Mushroom Fields", "", false);
  addMeal("nether_chili", MealEffects.FIREPROOF, 8, 180, "Nether", "", false);
  addMeal("ender_salad", MealEffects.FLOATING, 8, 180, "End", "", false);
  addMeal("garlic_bread", MealEffects.SUSTAINED, 8, 180, "Everyday", "", false);
  addMeal("cheesy_potato", MealEffects.HEARTY, 8, 180, "Everyday", "", false);
  addMeal("vegetable_pizza", MealEffects.SUSTAINED, 8, 180, "Everyday", "", false);
  addMeal("cornbread", MealEffects.SUSTAINED, 8, 180, "Everyday", "", false);
  addMeal("farmers_lunch", MealEffects.ENERGIZED, 8, 180, "Utility", "", false);
  addMeal("fishermans_stew", MealEffects.FISHER, 8, 180, "Utility", "", true);
  addMeal("builders_lunch", MealEffects.SUREFOOTED, 8, 180, "Utility", "", false);
  addMeal("explorers_meal", MealEffects.ENERGIZED, 8, 180, "Utility", "", false);
  addMeal("night_watch_stew", MealEffects.HERBAL, 8, 180, "Utility", "", true);
  addMeal("berry_pie", MealEffects.ENERGIZED, 8, 180, "Desserts", "", false);
  addMeal("chocolate_cake", MealEffects.MINER, 8, 180, "Desserts", "", false);
  addMeal("honey_tart", MealEffects.SWEET, 8, 45, "Desserts", "", false);
  addMeal("chorus_pie", MealEffects.FLOATING, 8, 180, "Desserts", "", false);
  addMeal("captains_chowder", MealEffects.SEAFOOD, 8, 180, "Ocean", "Shipwreck supply chests", false);
  addMeal("frost_garlic_soup", MealEffects.WARMING, 8, 180, "Frozen", "Igloo chests", true);
  addMeal("jungle_pepper_skewer", MealEffects.IRON_STOMACH, 8, 180, "Jungle", "Jungle temple chests", false);
  addMeal("marsh_rice_bowl", MealEffects.SUSTAINED, 8, 180, "Swamp", "Dungeon chests", false);
  addMeal("ancient_sap_pudding", MealEffects.SWEET, 12, 120, "Boss Cuisine", "", false);
  addMeal("prime_hunters_roast", MealEffects.FEAST, 12, 360, "Boss Cuisine", "", false);
  addMeal("restorative_broth", MealEffects.HEARTY, 12, 360, "Boss Cuisine", "", false);
  addMeal("tyrants_stock", MealEffects.SAVORY, 12, 360, "Boss Cuisine", "", false);
  addMeal("storm_omelette", MealEffects.ENERGIZED, 12, 360, "Boss Cuisine", "", false);
  addMeal("titan_curry", MealEffects.SAVORY, 12, 360, "Boss Cuisine", "", false);
  addMeal("witchs_gumbo", MealEffects.IRON_STOMACH, 12, 360, "Boss Cuisine", "", false);
  addMeal("mountain_bisque", MealEffects.SUREFOOTED, 12, 360, "Boss Cuisine", "", false);
  addMeal("hot_wyrm_stew", MealEffects.WARMING, 12, 360, "Boss Cuisine", "", false);
  addMeal("kraken_platter", MealEffects.SEAFOOD, 12, 360, "Boss Cuisine", "", false);
  addMeal("cavern_stew", MealEffects.MINER, 12, 360, "Boss Cuisine", "", false);
  addMeal("shadow_stew", MealEffects.HERBAL, 12, 360, "Boss Cuisine", "Ancient City chests", false);
  addMeal("sovereign_risotto", MealEffects.SWEET, 12, 120, "Boss Cuisine", "", false);
  addMeal("infernal_roast", MealEffects.FIREPROOF, 12, 360, "Boss Cuisine", "Bastion treasure chests", false);
  addMeal("soul_broth", MealEffects.SUSTAINED, 12, 360, "Boss Cuisine", "", false);
  addMeal("void_delight", MealEffects.FLOATING, 12, 360, "Boss Cuisine", "", false);
  addFeast("hunters_feast", MealEffects.FEAST, "");
  addFeast("woodland_feast", MealEffects.SWEET, "");
  addFeast("ocean_feast", MealEffects.SEAFOOD, "");
  addFeast("nether_feast", MealEffects.FIREPROOF, "");
  addFeast("ender_banquet", MealEffects.FLOATING, "");
  addFeast("hero_feast", MealEffects.FEAST, "Eat 20 distinct meals, or trade with a master Chef");
  for (BossKind kind : BossKind.values()) {
   String name = kind.id() + "_trophy";
   TROPHIES.put(kind, blockItem(name, new TrophyBlock(blockProperties(name))));
  }
  CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.FOOD_AND_DRINKS).register(entries -> {
   INGREDIENTS.values().forEach(entries::accept); DISHES.values().forEach(d -> entries.accept(d.item()));
  });
  CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.FUNCTIONAL_BLOCKS).register(entries -> {
   TROPHIES.values().forEach(entries::accept); entries.accept(COOKBOOK); SCROLLS.values().forEach(entries::accept);
  });
 }
}
