package darkspawn.black.boss;

public enum BossAttack {
	SLAM, BOULDERS, BROOD, CHARGE, BITE, SWEEP, ERUPTION, LIGHTNING, VOLLEY, WIND, STORM,
	VENOM, CONSTRICT, HEX, MIASMA, BLINK, FAULTLINE, FROST, BURROW, BLIZZARD,
	WAVE, INK, WHIRLPOOL, WATER_JET, WEB, POUNCE, ACID, SHADOW, SHADOW_STORM,
	SPORES, ROOTS, FUNGAL_GROWTH, FLAMES, MAGMA, SOUL_DRAIN, SOUL_CAGES, BEAM,
	SOUL_STORM, PORTAL, VOID_RIFTS
}
